# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/libreliu/code/GeometryPad

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/libreliu/code/GeometryPad

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/libreliu/code/GeometryPad/CMakeFiles /home/libreliu/code/GeometryPad/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/libreliu/code/GeometryPad/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GeoPad.elf

# Build rule for target.
GeoPad.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GeoPad.elf
.PHONY : GeoPad.elf

# fast build rule for target.
GeoPad.elf/fast:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/build
.PHONY : GeoPad.elf/fast

src/geo_generation.o: src/geo_generation.c.o

.PHONY : src/geo_generation.o

# target to build an object file
src/geo_generation.c.o:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_generation.c.o
.PHONY : src/geo_generation.c.o

src/geo_generation.i: src/geo_generation.c.i

.PHONY : src/geo_generation.i

# target to preprocess a source file
src/geo_generation.c.i:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_generation.c.i
.PHONY : src/geo_generation.c.i

src/geo_generation.s: src/geo_generation.c.s

.PHONY : src/geo_generation.s

# target to generate assembly for a file
src/geo_generation.c.s:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_generation.c.s
.PHONY : src/geo_generation.c.s

src/geo_obj_op.o: src/geo_obj_op.c.o

.PHONY : src/geo_obj_op.o

# target to build an object file
src/geo_obj_op.c.o:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_obj_op.c.o
.PHONY : src/geo_obj_op.c.o

src/geo_obj_op.i: src/geo_obj_op.c.i

.PHONY : src/geo_obj_op.i

# target to preprocess a source file
src/geo_obj_op.c.i:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_obj_op.c.i
.PHONY : src/geo_obj_op.c.i

src/geo_obj_op.s: src/geo_obj_op.c.s

.PHONY : src/geo_obj_op.s

# target to generate assembly for a file
src/geo_obj_op.c.s:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_obj_op.c.s
.PHONY : src/geo_obj_op.c.s

src/geo_point.o: src/geo_point.c.o

.PHONY : src/geo_point.o

# target to build an object file
src/geo_point.c.o:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_point.c.o
.PHONY : src/geo_point.c.o

src/geo_point.i: src/geo_point.c.i

.PHONY : src/geo_point.i

# target to preprocess a source file
src/geo_point.c.i:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_point.c.i
.PHONY : src/geo_point.c.i

src/geo_point.s: src/geo_point.c.s

.PHONY : src/geo_point.s

# target to generate assembly for a file
src/geo_point.c.s:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_point.c.s
.PHONY : src/geo_point.c.s

src/geo_register.o: src/geo_register.c.o

.PHONY : src/geo_register.o

# target to build an object file
src/geo_register.c.o:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_register.c.o
.PHONY : src/geo_register.c.o

src/geo_register.i: src/geo_register.c.i

.PHONY : src/geo_register.i

# target to preprocess a source file
src/geo_register.c.i:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_register.c.i
.PHONY : src/geo_register.c.i

src/geo_register.s: src/geo_register.c.s

.PHONY : src/geo_register.s

# target to generate assembly for a file
src/geo_register.c.s:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_register.c.s
.PHONY : src/geo_register.c.s

src/geo_test_code.o: src/geo_test_code.c.o

.PHONY : src/geo_test_code.o

# target to build an object file
src/geo_test_code.c.o:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_test_code.c.o
.PHONY : src/geo_test_code.c.o

src/geo_test_code.i: src/geo_test_code.c.i

.PHONY : src/geo_test_code.i

# target to preprocess a source file
src/geo_test_code.c.i:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_test_code.c.i
.PHONY : src/geo_test_code.c.i

src/geo_test_code.s: src/geo_test_code.c.s

.PHONY : src/geo_test_code.s

# target to generate assembly for a file
src/geo_test_code.c.s:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/geo_test_code.c.s
.PHONY : src/geo_test_code.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/main.c.s
.PHONY : src/main.c.s

src/shell.o: src/shell.c.o

.PHONY : src/shell.o

# target to build an object file
src/shell.c.o:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/shell.c.o
.PHONY : src/shell.c.o

src/shell.i: src/shell.c.i

.PHONY : src/shell.i

# target to preprocess a source file
src/shell.c.i:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/shell.c.i
.PHONY : src/shell.c.i

src/shell.s: src/shell.c.s

.PHONY : src/shell.s

# target to generate assembly for a file
src/shell.c.s:
	$(MAKE) -f CMakeFiles/GeoPad.elf.dir/build.make CMakeFiles/GeoPad.elf.dir/src/shell.c.s
.PHONY : src/shell.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... GeoPad.elf"
	@echo "... edit_cache"
	@echo "... src/geo_generation.o"
	@echo "... src/geo_generation.i"
	@echo "... src/geo_generation.s"
	@echo "... src/geo_obj_op.o"
	@echo "... src/geo_obj_op.i"
	@echo "... src/geo_obj_op.s"
	@echo "... src/geo_point.o"
	@echo "... src/geo_point.i"
	@echo "... src/geo_point.s"
	@echo "... src/geo_register.o"
	@echo "... src/geo_register.i"
	@echo "... src/geo_register.s"
	@echo "... src/geo_test_code.o"
	@echo "... src/geo_test_code.i"
	@echo "... src/geo_test_code.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shell.o"
	@echo "... src/shell.i"
	@echo "... src/shell.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

